### ISSUE TITLE
throw new Error('Can\'t set headers after they are sent.');

### ISSUE THREAD

**Issue by petrocel** [danwild/wind-js-server#3]
Hello,
I installed the server and for a few data works fine, but after 5 or 6  request,  ended with the following error (see error below): I'am not expert with the "express" library but I think that happens when people treat an asyn c response inside an express route as a synchronous response and they end up sending data twice. 
Thanks for your support
Alessandro
 
attempting to harvest older data 2017102200
response 200 | 2017102118
piping 2017102118
converted..
got older, no need to harvest further
2017102218 doesnt exist yet, trying previous interval..
2017102212 doesnt exist yet, trying previous interval..
_http_outgoing.js:356
    throw new Error('Can\'t set headers after they are sent.');
    ^

Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:356:11)
    at sendLatest (/home/ubuntu/wind-js-server-master/app.js:58:7)
    at /home/ubuntu/wind-js-server-master/app.js:62:5
    at /home/ubuntu/wind-js-server-master/node_modules/express/lib/response.js:430:22
    at onerror (/home/ubuntu/wind-js-server-master/node_modules/express/lib/response.js:1040:5)
    at Array.onfinish (/home/ubuntu/wind-js-server-master/node_modules/express/lib/response.js:1058:21)
    at listener (/home/ubuntu/wind-js-server-master/node_modules/on-finished/index.js:169:15)
    at onFinish (/home/ubuntu/wind-js-server-master/node_modules/on-finished/index.js:100:5)
    at callback (/home/ubuntu/wind-js-server-master/node_modules/ee-first/index.js:55:10)
    at Socket.onevent (/home/ubuntu/wind-js-server-master/node_modules/ee-first/index.js:93:5)

**Comment by petrocel** [comment]
The issue is not depending from the server but it was a problem based on how I called it.
Closed.
Thanks
